<script setup lang="ts">
import { computed } from 'vue'
import { useRouter } from 'vue-router'
import { useUserStore } from '@/stores/user'
const router = useRouter(); const user = useUserStore()
const isAdmin = computed(() => user.isAdmin)
function logout(){ user.logout(); void router.push({name:'login'}) }
</script>
<template><div class="management"><aside><button class="brand" @click="router.push({name:'chat'})">🌼 {{ isAdmin ? '幼教管理员控制台' : '幼教教师管理' }}</button><nav><small class="nav-title">{{ isAdmin ? '平台管理' : '课堂管理' }}</small><template v-if="isAdmin"><button @click="router.push({name:'teachers'})">教师管理</button><button @click="router.push({name:'classes'})">班级与学生</button><button @click="router.push({name:'student-center'})">学生管理中心</button><button @click="router.push({name:'devices'})">教室与设备</button><button @click="router.push({name:'classroom-scan'})">课堂设备准备</button></template><template v-else><button @click="router.push({name:'my-classes'})">我的班级</button><button @click="router.push({name:'lesson-plans'})">备课中心</button><button @click="router.push({name:'classroom-scan'})">课堂设备准备</button></template><small class="nav-title operations-title">课堂运营</small><button @click="router.push({name:'classroom-engagement'})">考勤与奖励</button><button @click="router.push({name:'classroom-insights'})">问题与作品</button><button @click="router.push({name:'classroom-remote'})">教师遥控</button></nav><button class="logout" @click="logout">退出登录</button></aside><main><header><span>{{ user.teacherInfo?.name || '当前账号' }} · {{ isAdmin ? '管理员' : '教师' }}</span><button @click="logout">退出</button></header><section class="content"><slot /></section></main></div></template>
<style scoped>.management{min-height:100dvh;display:flex;background:#fff8ee;color:#60483e}.management aside{width:240px;background:#fffaf2;border-right:1px solid #f2dfcf;padding:22px 14px;display:flex;flex-direction:column}.brand{border:0;background:none;font-size:19px;font-weight:800;color:#734d3c;text-align:left;padding:10px;cursor:pointer;white-space:nowrap}.management nav{display:grid;gap:6px;margin-top:32px}.nav-title{padding:0 12px 6px;color:#b47d62;font-size:11px;font-weight:800}.operations-title{margin-top:18px}.management nav button,.logout{border:0;background:none;text-align:left;color:#876b5d;padding:12px;border-radius:12px;cursor:pointer}.management nav button:hover{background:#ffeadc;color:#c96e45}.logout{margin-top:auto}.management main{flex:1;min-width:0}.management header{height:64px;background:#fffaf4;border-bottom:1px solid #f2dfcf;display:flex;justify-content:flex-end;align-items:center;gap:18px;padding:0 28px;color:#8a6d5f}.management header button{border:0;background:none;color:#df8b62;cursor:pointer}.content{max-width:1200px;margin:auto;padding:30px}.content h1{margin:0 0 8px;font-size:28px;color:#60483e}.muted{color:#a38270}.toolbar{display:flex;gap:10px;margin:22px 0}.toolbar input,.toolbar select{height:38px;border:1px solid #efd9c8;border-radius:12px;padding:0 11px;background:#fffdf9;color:#60483e}.button{border:0;background:#eb956b;color:#fff;border-radius:12px;padding:10px 16px;cursor:pointer}.panel{background:#fffdf9;border:1px solid #f0ddce;border-radius:16px;padding:18px;box-shadow:0 8px 24px #c88d6012}.table{width:100%;border-collapse:collapse}.table th,.table td{text-align:left;padding:13px 10px;border-bottom:1px solid #f4e6dc;font-size:14px}.badge{border-radius:12px;padding:4px 8px;font-size:12px}.ok{background:#e8f7ed;color:#4d9a69}.warn{background:#fff3dc;color:#b77d20}.bad{background:#ffebeb;color:#c64e4e}@media(max-width:700px){.management aside{width:60px;padding:12px 6px}.brand{font-size:0}.management nav button,.nav-title{font-size:0;text-align:center}.content{padding:18px}.management header{padding:0 15px}}
</style>
