<script setup lang="ts">
import { useRouter } from 'vue-router'
import { useUserStore } from '@/stores/user'
const router = useRouter(); const user = useUserStore()
function logout(){ user.logout(); void router.push({name:'login'}) }
</script>
<template><div class="management"><aside><button class="brand" @click="router.push({name:'chat'})">🌼 幼教管理</button><nav><button @click="router.push({name:'classes'})">班级与学生</button><button @click="router.push({name:'devices'})">教室与设备</button><button @click="router.push({name:'classroom-scan'})">扫码进课堂</button></nav><button class="logout" @click="logout">退出登录</button></aside><main><header><span>{{ user.teacherInfo?.name || '当前账号' }}</span><button @click="logout">退出</button></header><section class="content"><slot /></section></main></div></template>
<style scoped>.management{min-height:100dvh;display:flex;background:#f8fafc;color:#26364a}.management aside{width:220px;background:#fff;border-right:1px solid #e8edf3;padding:22px 14px;display:flex;flex-direction:column}.brand{border:0;background:none;font-size:19px;font-weight:800;color:#3b526b;text-align:left;padding:10px;cursor:pointer}.management nav{display:grid;gap:6px;margin-top:32px}.management nav button,.logout{border:0;background:none;text-align:left;color:#66788c;padding:12px;border-radius:8px;cursor:pointer}.management nav button:hover{background:#edf7f4;color:#229a7d}.logout{margin-top:auto}.management main{flex:1;min-width:0}.management header{height:64px;background:#fff;border-bottom:1px solid #e8edf3;display:flex;justify-content:flex-end;align-items:center;gap:18px;padding:0 28px;color:#6d7f91}.management header button{border:0;background:none;color:#3c9b80;cursor:pointer}.content{max-width:1200px;margin:auto;padding:30px}.content h1{margin:0 0 8px;font-size:28px}.muted{color:#8191a2}.toolbar{display:flex;gap:10px;margin:22px 0}.toolbar input,.toolbar select{height:38px;border:1px solid #dce5ed;border-radius:8px;padding:0 11px;background:#fff}.button{border:0;background:#36aa89;color:#fff;border-radius:8px;padding:10px 16px;cursor:pointer}.panel{background:#fff;border:1px solid #e7edf3;border-radius:12px;padding:18px}.table{width:100%;border-collapse:collapse}.table th,.table td{text-align:left;padding:13px 10px;border-bottom:1px solid #eef2f5;font-size:14px}.badge{border-radius:12px;padding:4px 8px;font-size:12px}.ok{background:#e6f7ef;color:#21936f}.warn{background:#fff3dc;color:#b77d20}.bad{background:#ffebeb;color:#c64e4e}@media(max-width:700px){.management aside{width:60px;padding:12px 6px}.brand{font-size:0}.management nav button{font-size:0;text-align:center}.content{padding:18px}.management header{padding:0 15px}}
</style>
