<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import ManagementLayout from '@/components/ManagementLayout.vue'
import { platformApi, type SchoolClass } from '@/api/platform'
import { apiErrorMessage } from '@/api/http'
const router = useRouter(); const items = ref<SchoolClass[]>([]); const loading = ref(true); const error = ref(''); const adding = ref(false); const saving = ref(false); const form = ref({ name: '', grade: '', ageRange: '', schoolYear: new Date().getFullYear().toString() })
const itemCount = computed(() => Array.isArray(items.value) ? items.value.length : 0)
async function load() { loading.value = true; error.value = ''; try { items.value = (await platformApi.classes()).data.items } catch { error.value = '班级加载失败，请检查登录状态后重试。' } finally { loading.value = false } }
async function create() { if (!form.value.name.trim() || !form.value.schoolYear.trim()) return; saving.value = true; try { await platformApi.createClass({ ...form.value, name: form.value.name.trim() }); form.value = { name: '', grade: '', ageRange: '', schoolYear: new Date().getFullYear().toString() }; adding.value = false; ElMessage.success('班级添加成功'); await load() } catch (cause) { ElMessage.error(apiErrorMessage(cause, '班级添加失败，请检查班级名称和学年。')) } finally { saving.value = false } }
async function toggle(item: SchoolClass) { const status = item.status === 'active' ? 'disabled' : 'active'; try { await platformApi.updateClass(item.id, { status }); ElMessage.success(status === 'active' ? '班级已恢复' : '班级已停用'); await load() } catch { ElMessage.error('班级状态更新失败') } }
onMounted(load)
</script>
<template><ManagementLayout><div class="page"><header><div><h1>班级与学生</h1><p>管理班级信息，并进入班级维护学生。</p></div><div class="toolbar"><button class="button" @click="load">刷新</button><button class="button" @click="adding = !adding">{{ adding ? '取消添加' : '添加班级' }}</button></div></header><div v-if="adding" class="panel add-form"><label>班级名称<input v-model="form.name" placeholder="如：小一班" /></label><label>年级<input v-model="form.grade" placeholder="如：小班" /></label><label>年龄段<input v-model="form.ageRange" placeholder="如：3-4岁" /></label><label>学年<input v-model="form.schoolYear" placeholder="如：2026-2027" /></label><button class="button" :disabled="saving || !form.name.trim() || !form.schoolYear.trim()" @click="create">{{ saving ? '保存中…' : '保存班级' }}</button></div><div class="panel"><p v-if="loading">加载中…</p><p v-else-if="error" class="bad">{{ error }} <button class="link" @click="load">重试</button></p><p v-else-if="!itemCount" class="muted">暂无班级，请先添加班级。</p><table v-else class="table"><thead><tr><th>班级</th><th>年级</th><th>年龄段</th><th>学年</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="item in items" :key="item.id"><td>{{ item.name }}</td><td>{{ item.grade || '—' }}</td><td>{{ item.ageRange || '—' }}</td><td>{{ item.schoolYear }}</td><td><span class="badge" :class="item.status === 'active' ? 'ok' : 'warn'">{{ item.status === 'active' ? '启用' : '停用' }}</span></td><td class="actions"><button class="link" @click="router.push({ name: 'students', params: { classId: item.id } })">查看学生</button><button class="link" @click="toggle(item)">{{ item.status === 'active' ? '停用' : '恢复' }}</button></td></tr></tbody></table></div></div></ManagementLayout></template>
<style scoped>.page{max-width:1180px;margin:auto}.page header{display:flex;justify-content:space-between;align-items:flex-end;gap:18px}.page h1{margin:0 0 8px;color:#60483e;font-size:40px}.page p{margin:0;color:#9a7e6e}.toolbar{display:flex;gap:10px}.button{border:0;border-radius:12px;padding:0 18px;min-height:42px;background:#e99168;color:#fff;font:inherit;cursor:pointer}.button:disabled{opacity:.55}.panel{margin-top:20px;padding:20px;border:1px solid #f0ddce;border-radius:18px;background:#fffdf9;box-shadow:0 10px 28px #b9795114}.add-form{display:grid;grid-template-columns:repeat(4,1fr) auto;align-items:end;gap:12px}.add-form label{display:grid;gap:6px;color:#876b5d;font-size:13px}.add-form input{height:40px;border:1px solid #efd9c8;border-radius:10px;padding:0 10px;background:#fffdf9}.table{width:100%;border-collapse:collapse;color:#60483e}.table th,.table td{text-align:left;padding:13px 10px;border-bottom:1px solid #f4e6dc}.badge{border-radius:999px;padding:5px 10px;font-size:12px}.ok{background:#e8f7ed;color:#4d9a69}.warn{background:#fff3dc;color:#b77d20}.link{border:0;background:none;color:#d67b59;cursor:pointer;margin-right:10px}.bad{color:#c64e4e}.muted{color:#9a7e6e}.actions{white-space:nowrap}@media(max-width:900px){.add-form{grid-template-columns:1fr 1fr}.page header{align-items:flex-start;flex-direction:column}}@media(max-width:600px){.add-form{grid-template-columns:1fr}.table{font-size:13px;display:block;overflow:auto;white-space:nowrap}}</style>
