<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import ManagementLayout from '@/components/ManagementLayout.vue'
import { platformApi, type Student } from '@/api/platform'
const route = useRoute(); const router = useRouter(); const classId = Number(route.params.classId); const items = ref<Student[]>([]); const loading = ref(true); const error = ref(''); const adding = ref(false); const saving = ref(false); const form = ref({ studentNo: '', name: '', nickname: '' })
async function load(){ loading.value = true; error.value = ''; try { items.value = (await platformApi.students(classId)).data.items } catch { error.value = '学生加载失败，请重试。' } finally { loading.value = false } }
async function create(){ if (!form.value.studentNo.trim() || !form.value.name.trim()) return; saving.value = true; error.value = ''; try { await platformApi.createStudent({ classId, studentNo: form.value.studentNo.trim(), name: form.value.name.trim(), nickname: form.value.nickname.trim() || undefined }); form.value = { studentNo: '', name: '', nickname: '' }; adding.value = false; await load() } catch { error.value = '添加学生失败，请检查学号是否重复或权限是否足够。' } finally { saving.value = false } }
onMounted(load)
</script>
<template><ManagementLayout><h1>学生列表</h1><p class="muted">班级 ID：{{ classId }} · {{ items.length }} 名学生</p><div class="toolbar"><button class="button" @click="router.push({name:'classes'})">返回班级</button><button class="button" @click="load">刷新</button><button class="button" @click="adding = !adding">{{ adding ? '取消添加' : '添加学生' }}</button><button class="button" @click="router.push({name:'class-rewards',params:{classId}})">🌟 成长奖励</button></div><div v-if="adding" class="panel add-form"><label>学号<input v-model="form.studentNo" maxlength="64" placeholder="请输入学号" /></label><label>姓名<input v-model="form.name" maxlength="100" placeholder="请输入姓名" /></label><label>昵称（可选）<input v-model="form.nickname" maxlength="100" placeholder="请输入昵称" /></label><button class="button" :disabled="saving || !form.studentNo.trim() || !form.name.trim()" @click="create">{{ saving ? '保存中…' : '保存学生' }}</button></div><div class="panel"><p v-if="loading">加载中…</p><p v-else-if="error" class="bad">{{ error }}</p><p v-else-if="!items.length">暂无学生</p><table v-else class="table"><thead><tr><th>头像</th><th>姓名</th><th>学号</th><th>状态</th><th></th></tr></thead><tbody><tr v-for="item in items" :key="item.id"><td>🧒</td><td>{{ item.name }}<small v-if="item.nickname">（{{ item.nickname }}）</small></td><td>{{ item.studentNo }}</td><td><span class="badge ok">{{ item.status }}</span></td><td><button class="button" @click="router.push({name:'student-profile',params:{studentId:item.id},query:{classId}})">资料</button></td></tr></tbody></table></div></ManagementLayout></template>
<style scoped>.add-form{display:grid;grid-template-columns:repeat(3,1fr) auto;align-items:end;gap:12px;margin-bottom:16px}.add-form label{display:grid;gap:6px;color:#876b5d;font-size:13px}.add-form input{height:38px;border:1px solid #efd9c8;background:#fffdf9;border-radius:10px;padding:0 10px}@media(max-width:800px){.add-form{grid-template-columns:1fr}}</style>
